services:
  database:
    build: ./db
    container_name: moni-postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - moni_net

  backend:
    build: .
    container_name: moni-be
    ports:
      - "8080:8080"
    restart: always
    networks:
      - moni_net
      - moni_fe_net
    depends_on:
      - database

  frontend:
    build: ./FE/moni-fe
    ports:
      - "3000:3000"
    networks:
      - moni_fe_net

networks:
  moni_net:
  moni_fe_net: