version: '3.9'
services:
  moni-be:
    build:
      context: .
      dockerfile: Dockerfile
    image: moni-be
    container_name: moni-be-compose
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - moni-data:/var/lib/postgresql/data
    depends_on:
      - moni-db
  moni-db:
    image: postgres:latest
    container_name: moni-db-compose
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pekka
      POSTGRES_DB: moni
    ports:
      - "5432:5432"
  moni-fe:
    build:
      context: ./FE/moni-fe
      dockerfile: Dockerfile
    image: moni-fe
    container_name: moni-fe-compose
    ports:
      - "4173:80"
    depends_on:
        - moni-be
volumes:
    moni-data:
      driver: local
